### ISSUE TITLE
Test case failed - test_swifter_apply_on_dataframe

### ISSUE THREAD

**Issue by msampathkumar** [jmcarpenter2/swifter#36] opened 2018-12-11 16:17 UTC
Hi @jmcarpenter2, if possible can you please do please check the test case named 'test_swifter_apply_on_dataframe' in `test/value_tests.py` - test case failed.  (please drop some suggestions)

code: **testing** branch of [https://github.com/msampathkumar/swifter](https://github.com/msampathkumar/swifter) )

**Comment by jmcarpenter2** [comment] 2018-12-14 16:55
Hi @msampathkumar,

Thanks so much for writing all these tests! This is a very exciting addition to the package. Once we get these merged, I will setup a CI/CD pipeline so that we can ensure that the tests are always passing on every build.

Regarding your question though: the issue is the default axis for pandas (axis=0) v. swifter (axis=1). Unfortunately, Dask doesn't have an axis=0 apply at the current time, referencing issue previously raised in swifter here:
https://github.com/jmcarpenter2/swifter/issues/10

I think this is a confusing issue at present, especially because most users of swifter will expect that the default is axis=0. I am just pushed an update to the code that will default to axis=0 instead of axis=1, but then raise a NotImplementedError referencing the issue.

Please update to v 0.280 and then re-run your tests.
`pip install swifter==0.280`

**Comment by msampathkumar** [comment] 2018-12-19 07:22
Awesome! Thank you.

**Closed** 2019-01-10 00:31 UTC
