### ISSUE TITLE
Swifter using only single core

### ISSUE THREAD

**Issue by raghu1121** [jmcarpenter2/swifter#45] opened 2019-03-18 20:10 UTC
I am applying swifter to a function which takes several values apart from `datetime` variable.
After running the code I saw it using only a single core (available 6 cores). The data is of size 476k rows. With a single core, it takes about 7.5 minutes. 

I added a `set_npartitions(16)` it improved the processing time to 3.5 minutes but still using a single core.

Any reason why it can't use all the cores?

**Comment by jmcarpenter2** [comment] 2019-03-19 01:09
Hi @raghu1121, 

Thanks for raising this issue. I would love to get to the bottom of your issue, but can you please provide some more information?

Can you provide the following:
1) the code for the function itself
2) the code you are using to call swifter on that function
3) the version of swifter that you have installed

Thanks,
Jason

**Comment by raghu1121** [comment] 2019-03-19 12:45
Thanks Jason for your reply.

Here is the code.

```
def clearness_index(time, Globalstrahlung):
    try:
        CI = util.clear_index(Globalstrahlung, lat, long,
                              tz.localize(pd.Timestamp(time)))
        if CI > 1:
            CI = 1
        return CI
    except ZeroDivisionError:
        return 0

df["clr_idx"] = df.swifter.set_npartitions(16).apply(lambda x: clearness_index(x['time'], x['GS_10']), axis=1)
```
I installed the version  0.283

**Comment by jmcarpenter2** [comment] 2019-04-09 20:40
Hi @raghu1121,

I apologize for the delay in my response. The past couple weeks have been intensely busy.

There was briefly a release of swifter where the default scheduler was set to "threads" instead of "processes". After realizing this mistake, the package was returned to utilizing "processes". The reason processes is a better default is that parallel processing generalizes to speed on more data types than multithreading does.

Can you please ` pip install swifter==0.284` just in case you are using that one release with the mistake?

Otherwise, I am not sure why you would be experiencing this issue. If the above pip install does not fix your problem, can you please share the `util` package you are using so I can recreate this issue locally and help debug more directly?

Thanks,
Jason

**Comment by raghu1121** [comment] 2019-04-10 08:22
Thanks, Jason for the response. It's still working the old way. I believe it is only a problem with this function, as it is a nested funtion. Please find the code for the util here. https://github.com/pingswept/pysolar/tree/master/pysolar 
Please let me know what could be done to speed up after your analysis.

Thanks,
Raghu

**Comment by jmcarpenter2** [comment] 2019-04-10 17:00
Hi @raghu1121,

It may be an issue with the specific function you are using, but I am confused now because I was able to download some public GHI data and run your code. On my machine I am spinning up multiple processes e.g. this photo from my activity monitor. Yours doesn't do this?

![Screen Shot 2019-04-10 at 9 43 22 AM](https://user-images.githubusercontent.com/29585347/55897343-316c6780-5b75-11e9-9d88-5b76f53ae663.png)

My understanding also agrees with this. Even though you are using control flow and exception handling, it should still be using multiple processes.

I also played around with using `np.where` to remove the `if` statement and speed up the code, but it made no difference in processing time. The issue is that the `try/catch` statement is limiting efficiency, but it seems like there isn't a good way around that unless you are able to handle whatever is causing that error before putting the data into `util.clear_index`.

I hope this helps, but if not feel free to come back with more questions.

Thanks,
Jason

**Comment by raghu1121** [comment] 2019-04-11 15:11
I removed the try catch and it seems to improve the performance, although it's still using a single core. But what surprised me was when I applied the same code to a small set of data (220k), everything worked just fine.

**Comment by jmcarpenter2** [comment] 2019-04-11 16:42
That's particularly strange.

Can you also try add `set_scheduler('processes')` to your chain of commands?

e.g. `df.swifter.set_dask_scheduler('processes').set_npartitions(16).apply(lambda x: clearness_index(x['time'], x['GS_10']), axis=1)`

Maybe this will force the usage of the `processes` scheduler on your machine.

Please let me know how that goes :)

**Comment by raghu1121** [comment] 2019-04-13 17:54
It seems to have a minimal impact though still using a single core.

**Comment by jmcarpenter2** [comment] 2019-04-13 21:44
I'm gonna be honest, I don't have a clue why it would work perfectly fine for 220k rows, but not for 476k rows. There is nothing in the code that differentiates between how many cores to use dependent on size of the data. 

Once swifter's logic reaches the dask stage, all is equal in terms of size of data.

**Comment by raghu1121** [comment] 2019-04-15 05:56
Even I don't have an explanation either! In the next few days, I will do a few more experiments and let you know any updates.

**Comment by raghu1121** [comment] 2019-04-25 12:38
I did a test with a different function which in turn calls several functions. The performance on this got even worse. I think this something to do with the function itself. You could give a try with `solar.get_altitude()`. The size of the sample is about half a million rows.

**Comment by jmcarpenter2** [comment] 2019-04-25 14:55
Oh man, of course!

The dataframe you are using must have a string column in it. I should've thought to mention this first! 

Well I'm glad that you were able to figure out the resolution to the issue!

**Comment by jmcarpenter2** [comment] 2019-04-29 00:15
Closing this issue because it seems resolved. Please feel free to re-open if you feel otherwise.

**Closed by jmcarpenter2** 2019-04-29 00:15 UTC

**Comment by jmcarpenter2** [comment] 2023-05-24 17:59
@vbangaru-wish yes you should be able to. Let me know if you have issues
