### ISSUE TITLE
Swifter With MultiProcessing

### ISSUE THREAD

**Issue by bilbusra** [jmcarpenter2/swifter#119] opened 2020-07-16 10:21 UTC
Hi,

I'm trying to use swifter with Processes for creating new columns from the existing ones. I mean I try to create multiple features(columns) by forking processes( `multiprocessing` library) and I also try to speed up the creation of a single column with swifter. 

- Is there any problem with this perspective? 

- When I try this, I get a `RecursionError: maximum recursion depth exceeded while calling a Python object
`. I searched this on Internet and I set the `sys.setrecursionlimit` to 5000( 1000 before) but it also did not work.

Thank you for your contribution in advance, Swifter helped me a lot.

**Comment by jmcarpenter2** [comment] 2020-07-16 15:43
Hi @bilbusra,

Thanks for raising this issue.

To help you debug the problem, could you please share the following information:

- Your versions of python, swifter, pandas, and dask
- A reproducible sample of code that causes the issue
- Any sample of related data necessary to run the code

With this information, I should be able to help you solve the problem :)

Thanks,
Jason

-

**Comment by bilbusra** [comment] 2020-07-22 19:54
Hi,
Sorry for the late reply. I solved the problem by using a different approach: my code was including a recursion and I removed it. I found that the recursion error was irrelevant with this issue. 

But I have still difficulties with using Swifter and` Process Start` (from `multiprocessing`) together. When a single column is created, it takes 3-4 hours, but when I use 2 process start with Swifter it took 20 hours.(Normally without the usage of `Process` it takes 8 hours. 


**Python version** :3.6.6 (Anaconda)
**Dask**:  0.19.2
**Pandas**: 0.23.4
**Swifter**: 0.305

Data is from [https://data.world/oklahoma/purchase-card-fiscal-year]

I'm trying to get the average amount of last 30 days transaction for every user. Maybe there is a more fancy way, but I couldn't figure it out. 

I also add necessary code parts to give you some idea about the problem.

Thanks in advance,
![func_for_process](https://user-images.githubusercontent.com/32414054/88222211-4b4c9380-cc6e-11ea-8955-3a4e9c2ac934.JPG)
![func_sample](https://user-images.githubusercontent.com/32414054/88222218-4be52a00-cc6e-11ea-9c72-7eb7cb29a2e3.JPG)
![sample_code_for_multiprocess](https://user-images.githubusercontent.com/32414054/88222219-4c7dc080-cc6e-11ea-8002-1e068de0769d.JPG)

**Comment by jmcarpenter2** [comment] 2020-07-31 16:04
Hi @bilbusra,

Thanks for sharing the code and data. I would like to add that there is a simpler way to do what you are trying to do, probably by using a rolling `df.swifter.rolling(...).apply(...)` or resampler apply `df.swifter.resample(...).apply(...)` rather than your current approach. 

Furthermore, it is an anti-pattern to use swifter from a forked process of another multiprocessing library. Swifter is already leveraging multiprocessing. So not only is it not necessary to use it from a forked process, but this can cause things to break as well due to sub-processes trying to leverage multiprocessing.

But yeah, I would definitely look into rolling and resample applies. 

Since this is not a bug in swifter, I'm going to close the issue.

Thanks,
Jason

**Closed by jmcarpenter2** 2020-07-31 16:04 UTC
