### ISSUE TITLE
swifter apply called too many times leading to wrong results

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [jmcarpenter2/swifter#80] opened 2019-11-01 11:20 UTC
Dear all,

Assume I want to apply a function to every row of a dataframe and store the result. If my df has a shape of [2,4] I will expect 8 items, with swifter I get 20.

```python
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df_tmp = df.head(2)

print(df_tmp.shape)

datas = []
def row2mongo(row, columns):
    index = row.name
    for col, name in zip(row, columns):
        data = {}
#         data = {'date': pd.to_datetime(index), 'name': name, 'value': float(col)}
        datas.append(data)
    
df_tmp.swifter.apply(partial(row2mongo, columns=df_tmp.columns), axis=1)

print(len(datas)) # [20] should be 8 
```

While using the default pandas .apply function I get the correct result

```python
datas = []

df_tmp.apply(partial(row2mongo, columns=df_tmp.columns), axis=1)

print(len(datas)) # [8] correct 

```

How it is possible? 

Thank you in advance,

Francesco Saverio

**Comment by jmcarpenter2** [comment] 2019-11-01 22:02
Hi @FrancescoSaverioZuppichini ,

Thanks for raising this issue, as I understand why this unexpected behavior might confuse a user. There are two issues here, which collectively have produced the situation you find yourself in.

1) Under the hood, `swifter` runs sample applies to test the time of the apply operation to determine the fastest approach for applying the function.

2) You are violating a core programming principle in your function's implementation. It is bad practice to modify an external variable from within a function (particularly without even passing that variable as a parameter into the function). In this example, you create variable `datas` outside of function `foo` (AKA `row2mongo`), and then modify `datas` within `foo` without even returning the variable `datas`.

Though you may be able to get away with this under a normal situation (e.g. using base pandas apply), it interacts with issue (1) in such a way that when `swifter` runs the sample applies, it is modifying the variable `datas` with each sample apply AND from the final apply that it chose as the fastest approach.

Swifter needs to do the sample applies to optimize the apply speed, so we can't really change that. Instead, my recommended solution to this issue is to rewrite your code so that you don't modify the external variable `datas` from within the function `foo`.  Below I have re-written your function `row2mongo` in such a way that it no longer modifies external variables and creates `datas` from within the dataframe and returns the value of datas. Since the pandas apply returns a pandas series, we can convert it to the expected list of dicts by using the function `itertools.chain`.

```python
import numpy as np
import pandas as pd
import swifter
from functools import partial
from itertools import chain
def row2mongo(row, columns):
    datas = []
    index = row.name
    for col, name in zip(row, columns):
        data = {'date': pd.to_datetime(index), 'name': name, 'value': float(col)}
        datas.append(data)
    return datas

datas = list(chain(*df_tmp.swifter.apply(partial(row2mongo, columns=df_tmp.columns), axis=1).tolist()))
print(len(datas)) # [8] correct 
```

I hope this resolves your issue. If this does not resolve your issue, please feel free to ask more questions. If it does, please close the issue at your convenience. Thank you.

**Comment by FrancescoSaverioZuppichini** [comment] 2019-11-02 11:41
Hi @jmcarpenter2,

Thank you for the super detailed answer and the solution. I perfectly understood the reason why it was not working. I think we can close the issue.

Thank you again.

Cheers, 

Francesco Saverio

**Comment by discdiver** [comment] 2019-11-04 12:30
Cool package! Thank you. This behavior makes sense, and should be mentioned in the docs so that users don't end up with unexpected results.

> Hi @FrancescoSaverioZuppichini ,
> 
> Thanks for raising this issue, as I understand why this unexpected behavior might confuse a user. There are two issues here, which collectively have produced the situation you find yourself in.
> 
> 1. Under the hood, `swifter` runs sample applies to test the time of the apply operation to determine the fastest approach for applying the function.
> 2. You are violating a core programming principle in your function's implementation. It is bad practice to modify an external variable from within a function (particularly without even passing that variable as a parameter into the function). In this example, you create variable `datas` outside of function `foo` (AKA `row2mongo`), and then modify `datas` within `foo` without even returning the variable `datas`.
> 
> Though you may be able to get away with this under a normal situation (e.g. using base pandas apply), it interacts with issue (1) in such a way that when `swifter` runs the sample applies, it is modifying the variable `datas` with each sample apply AND from the final apply that it chose as the fastest approach.
> 
> Swifter needs to do the sample applies to optimize the apply speed, so we can't really change that. Instead, my recommended solution to this issue is to rewrite your code so that you don't modify the external variable `datas` from within the function `foo`. Below I have re-written your function `row2mongo` in such a way that it no longer modifies external variables and creates `datas` from within the dataframe and returns the value of datas. Since the pandas apply returns a pandas series, we can convert it to the expected list of dicts by using the function `itertools.chain`.
> 
> ```python
> import numpy as np
> import pandas as pd
> import swifter
> from functools import partial
> from itertools import chain
> 
> def row2mongo(row, columns):
>     datas = []
>     index = row.name
>     for col, name in zip(row, columns):
>         data = {'date': pd.to_datetime(index), 'name': name, 'value': float(col)}
>         datas.append(data)
>     return datas
> 
> df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
> df_tmp = df.head(2)
> datas = list(chain(*df_tmp.swifter.apply(partial(row2mongo, columns=df_tmp.columns), axis=1).tolist()))
> print(len(datas)) # [8] correct 
> ```
> 
> I hope this resolves your issue. If this does not resolve your issue, please feel free to ask more questions. If it does, please close the issue at your convenience. Thank you.

**Comment by jmcarpenter2** [comment] 2019-11-07 19:44
Good point @discdiver!

I have added a note regarding this to the `docs/documentation.md` as well as the `README/md`. Also, thanks for your great Towards Data Science article on `swifter`!

Closing this issue now.

Thanks,
Jason

**Closed by jmcarpenter2** 2019-11-07 19:44 UTC
